### ISSUE TITLE
Plugin only shows the first 25 episodes

### ISSUE THREAD

**Issue by MrsAngelD** [Sinap/plugin.video.funimation#1]
My hubby likes to watch fairy tail, there are 51 shows but for some reason the plugin only shows the first 25.

**Comment by Shadoxfix** [comment]
I've noticed this issue as well. It seems that the API does not return all episodes in some cases. http://www.funimation.com/mobile/episodes.json/subscription/sequence/asc/all/381 only returns episode 1 to 25. The same happens for Psycho-Pass where only episode 1-22 + specials are available and the second season missing. (episode 23+)

**Comment by Shadoxfix** [comment]
I actually found the solution to this. Specifying no page will always return page 0. Using http://www.funimation.com/mobile/episodes.json/subscription/sequence/asc/all/381?page=1, http://www.funimation.com/mobile/episodes.json/subscription/sequence/asc/all/381?page=2 etc. will actually show all episodes. Looks like the API has to go through all pages that exist.

**Comment by afrase** [comment]
What settings do you have set? Specifically do you have an account setup (is it an elite account or normal) and are you only showing subtitled, dubbed or both?
Is there a "More Results" item at the bottom?
I'm showing 214 subtitled episodes and 164 dubbed with an account.

**Comment by MrsAngelD** [comment]
Ok I was prepared to write you back and answer all your questions, when I discovered it was a problem with list view and my skin....lol. Disregard this whole issue as it seems the plugin is working great. :)
