### ISSUE TITLE
unable to play videos

### ISSUE THREAD

**Issue by rivnam** [Sinap/plugin.video.funimation#14]
Hi, 

I am having connection issues with the addon within the last week. was using free version OK but then upgraded to the subscription and it did not work. Now default settings also do not work and where before I was getting a list of videos I am now also not getting that either. I have the following log output of the most recent windows fail (issue also on android box will try to get log). 

http://pastebin.com/embed_js.php?i=97R4bJT1

<script src="http://pastebin.com/embed_js.php?i=97R4bJT1"></script>

The funimation website and android app work and i updated to the latest win7 kodi build but alas still no funimation in kodi. (Crunchyroll works)

i hope you can help, thanks in advance

**Comment by afrase** [comment]
Line 4 of the log has
`<urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>`

You get `<urlopen error [Errno 61] Connection refused>` when the server or your internet is down. I think when the connection is actively refused it means the server either dropped the packet or sent a TCP reset (RST).

You could try clearing all of the addon data by delete everything in `C:\Users\m\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.funimation`

Let me know how that goes.

-Aaron

**Comment by rivnam** [comment]
deleted everything, uninstalled the addon, relaunched Kodi, installed a fresh copy via the repo and....same error in log. 

http://pastebin.com/qbbc8gah

Is the "Error Type: <class 'urllib2.URLError" significant?

So, a similar thing is happening on my android box. double checked and the website is working and streaming, so theres still that i guess. 

gonna try an older build and see what happens....same errors.

could it be related to video preferences on funimation's site? I had set to 1080p, sub. Am unable to "unselect" those options now, only a variation on sd, hd 720, hd 1080 and dub/dub.

**Comment by afrase** [comment]
The `Error Type: <class 'urllib2.URLError` is just the error class.

I don't think the settings form the site will matter.

If you set the `Log Level` to `Debug` in the settings it will output the URL it calls. Just look for `plugin.video.funimation] _build_request :`.
The simultcast URL is `https://www.funimation.com/feeds/ps/shows?filter=FilterOptionSimulcast&ut=FunimationUser&limit=1000&offset=0`

It could be that the server you are connecting to doesn't have TLS/SSL support for some reason. You could try editing the `api.py` file in `plugin.video.funimation/resources/lib/funimation` on line 16 change `https://www.funimation.com/` to `http://www.funimation.com/`

**Comment by rivnam** [comment]
Yeah, that's fixed it on windows.  Thanks very much for the help.
