### ISSUE TITLE
Incomplete episode listing

### ISSUE THREAD

**Issue by Choppasmith** [Sinap/plugin.video.funimation#15]
There currently seems to be an issue where any show I pull up only shows the first 4 or so episodes (if it shows sub and dub) it'll show 8 items all together. Maybe Funimation altered the code slightly? Should note, I'm a free user with no account.

**Comment by afrase** [comment]
Make sure you are logged in. A free account will only show the first few episodes.
Can you give me an example of a show and how many episodes it shows?

**Comment by Choppasmith** [comment]
I've tried both One Piece and Hetalia and they both showed 8 videos available (dub and sub for 4 episodes). And yeah, looking at their official page, it looks like they've changed up their content and what's free. Before I could scroll through and watch several episodes of One Piece dubbed and even keep up with the sub simulcast all without having an account. But yeah it looks like I at least need an account to access more of the content, I'll try registering and see how different my experience is and get back to you, but I have the feeling it's their end and not yours.

**Comment by afrase** [comment]
You didn't hear this from me, but you might want to check the `api.py` file in the plugin source directory.

**Comment by Choppasmith** [comment]
Uhh well, I see where you're going there but I'm not quite sure what to change anyway, but thanks all the same :) I signed up for the free account, still got the same thing, decided to apply for a 1 month all access pass and got everything and that's good enough. Thanks for your help.

**Comment by afrase** [comment]
No problem :)
