### ISSUE TITLE
Trakt / library integration 

### ISSUE THREAD

**Issue by Protocol-X** [Sinap/plugin.video.funimation#21]
I have not seen any updates in 4 months, so I am not sure if this is plugin is still actively worked on, but if it is could trakt api integration be added as well as library?

Thanks

**Comment by BlackHeart-TF** [comment]
you mean to include the content from funimation so it appears in a local library?

i have no idea how trakt works in general, as i heard about it just now in your post. but i would assume if xbmc/kodi does it already, it shouldn't be too hard, if it doesn't already :P

**Comment by Protocol-X** [comment]
Are you the developer or just a user?

**Comment by BlackHeart-TF** [comment]
not "the" developer, but trying to get in contact with them. if i can't, going to fork it and continue work on it

**Comment by Protocol-X** [comment]
I actually just finished rewriting it from scratch. It has the login
prompt, and all the features it was missing, plus trakt integration. I'm
just finishing a few last minute things.  Should be 100% by the weekend.
Since the developers have not responded and I see no updates in a while I
think it is dead.

**Comment by BlackHeart-TF** [comment]
oh haha i was just working on a better login setup. cant wait to see yours :P

**Comment by Protocol-X** [comment]
You are welcome to take it over as I was just building it to make it
better, not sure if I will be able to keep it up to date..   And I'm not
overly familiar with how to get addons added to the repository.  Is there a
way to contact you privately?

**Comment by afrase** [comment]
Sorry for not posting any updates for so long. I've been busy lately and my laptop also died so I haven't been doing development work at home.
I would like to start working on finishing the Funimation Now API and updating the plugin to use Kodiswift for the UI. (fork of xbmcswift I made) Hopefully this weekend or sometime this month I'll start pushing updates to that.

@Protocol-X Could your rewrite be merged or are there to many changes for that?

**Comment by Protocol-X** [comment]
It is a complete rewrite so I do not believe it can be merged.   I have
never had any custom ui's in kodi that looked good and worked well they are
all very intrusive.

What is kodiswift exactly?

The rewrite includes support for everything.   Better multi user support,
history, favorites, queue, trakt ect.  Image type, quality and so on.  The
only thing I haven't had a chance to implement yet that I wanted is a user
option to integrate the anime queue into the user library if the user
wanted, like salts or specto, but instead of having to manually add, it
just syncs your queue.

I am willing to provide the full code if you keep my name on it as well and
you do not remove the added features.

**Comment by BlackHeart-TF** [comment]
i could look into merging them the ol' fashioned way at some point, until the new api one is done.

**Comment by BlackHeart-TF** [comment]
also @Sinap if you need some different platform testing for that, i have a boatload of different xbmc/kodi setups including Apple TV, xbox, android, iOS, and the big 3 computer OSes

**Comment by Protocol-X** [comment]
@ShadowNoire Send me your email and I'll be in contact with you both over the weekend

**Comment by ShadowNoire** [comment]
noire@gmx.ca

**Comment by BlackHeart-TF** [comment]
we could do up a thing on Skype or discord to talk about it
