### ISSUE TITLE
Funimation Account Logon

### ISSUE THREAD

**Issue by sauron2100** [Sinap/plugin.video.funimation#3]
Any chance for adding support for Funimation paid subscribers?  Queue support and subscriber only videos would be nice.

**Comment by afrase** [comment]
You can add your login credentials in the settings. If you're a paid subscriber you will be able to see the paid videos but the API doesn't show if a particular video is paid only.

**Comment by sauron2100** [comment]
That works.  I couldn't find where to add my credentials.

Thank you!
