### ISSUE TITLE
No need for a dub/sub only option

### ISSUE THREAD

**Issue by scj643** [Sinap/plugin.video.funimation#9]
This is already built into kodi which can be done with the filter menu option with (dub) or (sub) respectively

**Comment by afrase** [comment]
Is there a way to make the filter persist when changing menus?

**Comment by scj643** [comment]
Sadly no, but it is useful if you have kodi set to play all videos at once. Or it would be if it worked.

**Comment by afrase** [comment]
It will be simple to add an option to filter sub/dub videos so I'll probably add it anyway.
